// models/OrderSchema.js
const mongoose = require('mongoose');

const orderItemSchema = new mongoose.Schema({
  productId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true },
  name: { type: String, required: true },
  price: { type: Number, required: true },
  quantity: { type: Number, required: true, min: 1 }
}, { _id: false });

const orderSchema = new mongoose.Schema({
  orderNumber: { type: String, unique: true, index: true },
  customer: {
    name: String,
    email: String,
    address: String,
    city: String,
    otherCity: String,
    postalCode: String,
    mobile: String
  },
  items: [orderItemSchema],
  subtotal: { type: Number, required: true },
  shippingRate: { type: Number, required: true },
  shippingCost: { type: Number, required: true },
  totalCost: { type: Number, required: true },
  discountAmount: { type: Number, default: 0 },
  finalAmount: { type: Number, default: 0 },
  paymentMode: { type: String, enum: ['prepaid', 'cod', 'free'], default: 'cod' },
  paymentDetails: {
    methodId: { type: mongoose.Schema.Types.ObjectId, ref: 'PaymentMethod', default: null },
    methodName: { type: String, default: '' },
    methodCode: { type: String, default: '' },
    receiptUrl: { type: String, default: '' },
    paymentDiscount: { type: Number, default: 0 },
    paymentCharge: { type: Number, default: 0 },
    payableAmount: { type: Number, default: 0 },
    isVerified: { type: Boolean, default: false },
    verifiedAt: { type: Date, default: null },
    verifiedByName: { type: String, default: '' },
    codDeliveryCharges: { type: Number, default: 0 },
    codNetReceived: { type: Number, default: 0 },
    deliveryExpenseEntryId: { type: mongoose.Schema.Types.ObjectId, ref: 'ExpenseEntry', default: null },
  },
  status: {
    type: String,
    enum: ['pending_confirmation', 'confirmed', 'rejected', 'dispatched', 'delivered', 'returned', 'cancelled'],
    default: 'pending_confirmation'
  },
  rejectionReason: { type: String, default: '' },
  courier: {
    courierId: { type: mongoose.Schema.Types.ObjectId, ref: 'Courier', default: null },
    courierName: { type: String, default: '' },
    trackingNumber: { type: String, default: '' },
    courierHelpline: { type: String, default: '' },
    jmmContactPersonName: { type: String, default: '' },
    jmmContactNumber: { type: String, default: '' },
    provider: { type: String, default: '' },
    slipLink: { type: String, default: '' },
    latestStatus: { type: String, default: '' },
    latestStatusAt: { type: Date, default: null },
    latestStatusRemarks: { type: String, default: '' },
    latestStatusRaw: { type: mongoose.Schema.Types.Mixed, default: null },
  },
  adminRemarks: { type: String, default: '' },
  giftInfo: {
    isGift: { type: Boolean, default: false },
    giftType: { type: String, enum: ['none', 'owner', 'customer'], default: 'none' },
    ownerGiftSourceId: { type: mongoose.Schema.Types.ObjectId, ref: 'GiftSource', default: null },
    ownerGiftSourceName: { type: String, default: '' },
    senderName: { type: String, default: '' },
    senderContact: { type: String, default: '' },
    senderAddress: { type: String, default: '' },
    giftPaymentType: { type: String, enum: ['none', 'prepaid', 'pay_later'], default: 'none' },
    giftAmount: { type: Number, default: 0 },
    giftNote: { type: String, default: '' },
    markedAt: { type: Date, default: null },
    markedByName: { type: String, default: '' },
  },
  notes: [{
    text: { type: String, default: '' },
    createdAt: { type: Date, default: Date.now },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
    createdByName: { type: String, default: '' },
  }],
  feedback: {
    rating: { type: Number, min: 1, max: 5, default: null },
    comments: { type: String, default: '' },
    submittedAt: { type: Date, default: null },
  },
  statusTimeline: {
    placedAt: { type: Date, default: Date.now },
    confirmedAt: { type: Date, default: null },
    dispatchedAt: { type: Date, default: null },
    deliveredAt: { type: Date, default: null },
    cancelledAt: { type: Date, default: null },
    returnedAt: { type: Date, default: null },
  },
  customerConfirmation: {
    status: { type: String, enum: ['none', 'confirmed', 'cancelled'], default: 'none' },
    respondedAt: { type: Date, default: null },
    responseSource: { type: String, default: '' },
    responseMessageId: { type: String, default: '' },
    responseText: { type: String, default: '' },
  },
  createdByAdmin: {
    isAdminCreated: { type: Boolean, default: false },
    createdByName: { type: String, default: '' },
    createdAt: { type: Date, default: null },
    customerAlreadyConfirmed: { type: Boolean, default: false },
  },
  stockReservation: {
    isReserved: { type: Boolean, default: false },
    reservedSiteId: { type: mongoose.Schema.Types.ObjectId, ref: 'Site', default: null },
    reservedSiteName: { type: String, default: '' },
    reservedAt: { type: Date, default: null },
    reservedByName: { type: String, default: '' },
    items: [{
      productId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
      productName: { type: String, default: '' },
      requestedQty: { type: Number, default: 0 },
      reservedQty: { type: Number, default: 0 },
    }],
    onlineDispatchDeductedAt: { type: Date, default: null },
    onlineDispatchDeductedByName: { type: String, default: '' },
  },
  stockRequest: {
    requestId: { type: mongoose.Schema.Types.ObjectId, default: null },
    status: { type: String, enum: ['none', 'pending', 'accepted', 'rejected', 'cancelled'], default: 'none' },
    sourceSiteId: { type: mongoose.Schema.Types.ObjectId, ref: 'Site', default: null },
    sourceSiteName: { type: String, default: '' },
    requestedAt: { type: Date, default: null },
    requestedByName: { type: String, default: '' },
    respondedAt: { type: Date, default: null },
    respondedByName: { type: String, default: '' },
  },
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Order', orderSchema);
